### ISSUE TITLE
Timeline Render Issue

### ISSUE THREAD

**Issue by Justin-Lund** [funny-cat-happy/joplin-plugin-TimelineRender#2]
Hi there,

I tried putting in the a date, and it seems to be subtracting a day from the dates I'm entering.

I saw your changelog mention there was a previous issue with time in a different country - so for context, I'm in BC Canada, on Pacific Time (PT). We're currently in daylight savings, so we are in the PDT timezone (GMT -7)

![image](https://user-images.githubusercontent.com/47057520/227447834-0b3f9230-acbf-463a-a56c-2f06ef2c0c9c.png)

Edit: I just realized the issue is happening specifically when I write the date as 2022-03-23 instead of 2022-3-23. The 0 breaks the date. I threw it into ChatGPT which said it was an issue with a lack of zero-padding, & suggested the following:

_To fix the issue, you can modify the code to ensure that the month and day are zero-padded before passing the input string to the Date constructor. You can do this by adding a padding function to the code, like so:_

```js
function zeroPad(num) {
  return num.toString().padStart(2, '0');
}
```

_Then, you can modify the line that creates the date object as follows:_
```js
let parts = clearContent.split('-');
let year = parts[0];
let month = zeroPad(parts[1]);
let day = zeroPad(parts[2]);
time = new Date(`${year}-${month}-${day}`);
```

I'm not super competent with javascript so I don't know how to re-render the plug-in to test, but hope that helps.
Thanks for making this plugin!

**Comment by funny-cat-happy** [comment]
Hello guy,
I find the reason of the problem and try to fix it.But I don't whether it is ok because I can't take my computer to Canada.haha.If the problem still exists,please inform me.You can update the plugin via github release or npm.
As for the reason,in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date Date string Note.
```
Date-only strings (e.g. "1970-01-01") are treated as UTC, while date-time strings (e.g. "1970-01-01T12:00") are treated as local. You are therefore also advised to make sure the input format is consistent between the two types.
```
If your input is 2022-03-22 in GMT -7 timezone,your time is earlier than UTC.So the date is subtracting a day.
Thank you for your feedback
