### ISSUE TITLE
Able to use other time formats than US format

### ISSUE THREAD

**Issue by ursus69** [funny-cat-happy/joplin-plugin-TimelineRender#4]
# Ability to use other date formats than US format.

I would be greta for those of us that do not live or work in USA to be able to use other date formats:
for example in France and Spain we use the date like:

`25-12-2024` instead of `2024-12-25`

**Comment by Spreadcat** [comment]
Exactly what I also stumbled about. But the US format would be `12-25-2024` IIRC, while the format `2024-12-25` would be the international on. The format you reference `25-12-2024` is more a local/european one IMHO.

I was playing around with a regex supporting these formats and times as well:

```regex
2024-01-01
2024-1-1 19:00
2024-01-01 18:00
18:00
18:00:23
2024-01-91 23:01:15
```

and ended up with this so far: `^(\d{4}-\d{1,2}-\d{1,2})?(\ ?(\d{2})\:(\d{2})(\:\d{2}?)?)?`. 
It's not pretty, but works for me. When I tried to add it and put in a PR, i discovered som date handling further down in `Timeline.js`, which then would require med to install the NPM dependencies in order to verify it's working. That's a bit more than I am willing to invest at the moment, just to be able to use the plugin which currently is limited to dates only and not hours.

**Comment by funny-cat-happy** [comment]
thank for your feedback. But I am very buzy recently. I will add a time config to a menu and code refact to typescript at June.

**Comment by Del95** [comment]
The possibility to have only one year and/or month as date would be great as well ;-)

**Comment by funny-cat-happy** [comment]
In new version,you can go to menu option to set time format.

**Comment by Spreadcat** [comment]
yepp, it's working. I can now use `2024-01-01 18:00:01` formatted timelines. The european version with `01-01-2024` or `01.01.2024` (more used) is working as well.

Thanks for adding this.
